LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

LOCAL_MODULE := eszFW

LOCAL_SRC_FILES := $(LOCAL_PATH)/esz.c

LOCAL_CFLAGS := -D_REENTRANT -DWANT_ZLIB

LOCAL_LDLIBS := -lz

LOCAL_STATIC_LIBRARIES :=
LOCAL_SHARED_LIBRARIES := tmx SDL2 SDL2_image

include $(BUILD_SHARED_LIBRARY)
