<?xml version="1.0" encoding="UTF-8"?>
<tileset name="MagicCliffsEnvironment" tilewidth="16" tileheight="16" tilecount="1160" columns="58">
 <image source="tileset.png" width="928" height="320"/>
 <tile id="118" type="Platform"/>
 <tile id="119" type="Platform"/>
 <tile id="120" type="Platform"/>
 <tile id="121" type="Platform"/>
 <tile id="122" type="Platform"/>
 <tile id="123" type="Platform"/>
 <tile id="124" type="Platform"/>
 <tile id="194" type="Platform"/>
 <tile id="195" type="Platform"/>
 <tile id="196" type="Platform"/>
 <tile id="197" type="Platform"/>
 <tile id="199" type="Platform"/>
 <tile id="201" type="Platform"/>
 <tile id="202" type="Platform"/>
 <tile id="203" type="Platform"/>
 <tile id="204" type="Platform"/>
 <tile id="265" type="Platform"/>
 <tile id="266" type="Platform"/>
 <tile id="267" type="Platform"/>
 <tile id="269" type="Platform"/>
 <tile id="270" type="Platform"/>
 <tile id="271" type="Platform"/>
 <tile id="272" type="Platform"/>
 <tile id="440" type="Platform"/>
 <tile id="441" type="Platform"/>
 <tile id="442" type="Platform"/>
 <tile id="443" type="Platform"/>
 <tile id="467" type="Platform"/>
 <tile id="468" type="Platform"/>
 <tile id="469" type="Platform"/>
 <tile id="473" type="Platform"/>
 <tile id="474" type="Platform"/>
 <tile id="698" type="Platform"/>
 <tile id="699" type="Platform"/>
 <tile id="700" type="Platform"/>
 <tile id="701" type="Platform"/>
 <tile id="702" type="Platform"/>
 <tile id="703" type="Platform"/>
 <tile id="705" type="Platform"/>
 <tile id="706" type="Platform"/>
 <tile id="708" type="Platform"/>
 <tile id="709" type="Platform"/>
 <tile id="710" type="Platform"/>
 <tile id="712" type="Platform"/>
 <tile id="713" type="Platform"/>
 <tile id="715" type="Platform"/>
 <tile id="716" type="Platform"/>
 <tile id="718" type="Platform"/>
 <tile id="720" type="Platform"/>
 <tile id="721" type="Platform"/>
 <tile id="723" type="Platform"/>
 <tile id="724" type="Platform"/>
 <tile id="726" type="Platform"/>
 <tile id="728" type="Platform"/>
 <tile id="729" type="Platform"/>
 <tile id="730" type="Platform"/>
 <tile id="733" type="Platform"/>
 <tile id="734" type="Platform"/>
 <tile id="735" type="Platform"/>
 <tile id="736" type="Platform"/>
 <tile id="737" type="Platform"/>
 <tile id="738" type="Platform"/>
 <tile id="739" type="Platform"/>
 <tile id="740" type="Platform"/>
</tileset>
